spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: jsbbsj
    username: root
#    type:org.apache.commons.dbcp2.BasicDataSource

mybatis:
  configuration:
    map-underscore-to-camel-case: true
