spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: jsbbsj
    username: root
  redis:
    host: 127.0.0.1
    port: 6379

#    type:org.apache.commons.dbcp2.BasicDataSource

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml

server:
  servlet:
    session:
      timeout:

